### ISSUE TITLE
Try to support Python 3.6.7

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/cogs#103]
It looks like `add_subparser` did not support `required` in 3.6:

```
Traceback (most recent call last):
  File "/users/joverton/IMPACC2ImmPort/_venv/bin/cogs", line 11, in <module>
    sys.exit(main())
  File "/users/joverton/IMPACC2ImmPort/_venv/lib/python3.6/site-packages/cogs/cli.py", line 73, in main
    subparsers = parser.add_subparsers(required=True, dest="cmd")
  File "/programs/x86_64-linux/python/3.6.5/lib/python3.6/argparse.py", line 1707, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
```

Once I remove that, most things seem to work.

**Comment by jamesaoverton** [comment]
It would also be good to test multiple Python versions with GitHub actions, like we are now doing for VALVE.
